package com.example.postgresql.model;

import java.io.Serializable;
import java.util.Map;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Size;

/**
 * The Class ApplicationJobDataReqDTO.
 */
public class ApplicationJobDataReqDTO implements Serializable {

  /** The Constant serialVersionUID. */
  private static final long serialVersionUID = 1L;

  /**
   * Unique identifier, auto-generated by the application. Read-only.
   */
  @Size(min = 36, max = 36)
  @Schema(title = "Unique identifier, auto-generated by the application. Read-only.", accessMode = Schema.AccessMode.READ_ONLY)
  private String entityId;

  /** The app id. */
  @Size(min = 36, max = 36)
  @Schema(title = "Unique identifier for the applicaton batch Process.", accessMode = Schema.AccessMode.READ_ONLY)
  private String appId;

  /** The job bean class name. */
  @Size(max = 256)
  @Schema(title = "Job Bean Class Name, must be a valid Bean", example = "@Bean(name = FeraJobBeanConstants.FEBP_JOB_BEAN_FERA_CONSOLIDATED_STATEMENT_REPORT)",accessMode = Schema.AccessMode.READ_ONLY)
  private String appJobBeanName="FEBP_EMP_TAX_CALCULATION";

  /** The job bean class name. */

  @Schema(title = "Job Restart Execution ID", example = "1881")
  private String appRestartJobExecutionId;

  /** The app job params map. */
  @Schema(title = "Required Job parameters", example = "key:value of type JobParameter",accessMode = Schema.AccessMode.READ_ONLY)
  private Map<String, Object> appJobParamsMap;

  /**
   * Instantiates a new application job data req DTO.
   *
   * @param entityId                 the entity id
   * @param appId                    the app id
   * @param appJobBeanName           the app job bean name
   * @param appRestartJobExecutionId the app restart job execution id
   * @param appJobParamsMap          the app job params map
   */
  public ApplicationJobDataReqDTO(@Size(min = 36, max = 36) String entityId, @Size(min = 36, max = 36) String appId, @Size(max = 256) String appJobBeanName,
      String appRestartJobExecutionId, Map<String, Object> appJobParamsMap) {
    super();
    this.entityId = entityId;
    this.appId = appId;
    this.appJobBeanName = appJobBeanName;
    this.appRestartJobExecutionId = appRestartJobExecutionId;
    this.appJobParamsMap = appJobParamsMap;
  }

  /**
   * Instantiates a new application job data req DTO.
   */
  public ApplicationJobDataReqDTO() {

  }

  /**
   * Gets the entity id.
   *
   * @return the entity id
   */
  public String getEntityId() {
    return entityId;
  }

  /**
   * Sets the entity id.
   *
   * @param entityId the new entity id
   */
  public void setEntityId(String entityId) {
    this.entityId = entityId;
  }

  /**
   * Gets the app id.
   *
   * @return the app id
   */
  public String getAppId() {
    return appId;
  }

  /**
   * Sets the app id.
   *
   * @param appId the new app id
   */
  public void setAppId(String appId) {
    this.appId = appId;
  }

  /**
   * Gets the app job bean name.
   *
   * @return the app job bean name
   */
  public String getAppJobBeanName() {
    return appJobBeanName;
  }

  /**
   * Sets the app job bean name.
   *
   * @param appJobBeanName the new app job bean name
   */
  public void setAppJobBeanName(String appJobBeanName) {
    this.appJobBeanName = appJobBeanName;
  }

  /**
   * Gets the app restart job execution id.
   *
   * @return the app restart job execution id
   */
  public String getAppRestartJobExecutionId() {
    return appRestartJobExecutionId;
  }

  /**
   * Sets the app restart job execution id.
   *
   * @param appRestartJobExecutionId the new app restart job execution id
   */
  public void setAppRestartJobExecutionId(String appRestartJobExecutionId) {
    this.appRestartJobExecutionId = appRestartJobExecutionId;
  }

  /**
   * Gets the app job params map.
   *
   * @return the app job params map
   */
  public Map<String, Object> getAppJobParamsMap() {
    return appJobParamsMap;
  }

  /**
   * Sets the app job params map.
   *
   * @param appJobParamsMap the app job params map
   */
  public void setAppJobParamsMap(Map<String, Object> appJobParamsMap) {
    this.appJobParamsMap = appJobParamsMap;
  }

}
